### ISSUE TITLE
Doesn't work in IE11-

### ISSUE THREAD

**Issue by Calvein** [d3/d3-color#15]
I'm not sure if it's an actual issue because I don't know the browser support for this but [Map](https://github.com/d3/d3-color/blob/3767ff95cbe59625cf6f3997449b5987919ad852/src/color.js#L37) isn't supported in IE10- and in IE11, [`Map.prototype.set` does't return `this`](http://kangax.github.io/compat-table/es6/#Map_Map.prototype.set_returns_this).

**Comment by mbostock** [comment]
The lack of universal support for Map is why this module is built with --polyfill-map. And d3/d3-bundler@ebe9915c36b5bd08bb23a6971cdcd6471218e715 added a fix for map.set not returning this. So, assuming you are running the latest release, you should either be getting the complete Map polyfill in IE10- or the patched map.set in IE11. Could you verify that you are using the latest release, and help me debug how the code isn’t working on IE?

Related #16.
