### ISSUE TITLE
Add CIECAM02.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-color#21]
Possibly a better perceptual colorspace than Lab/Lch and Cubehelix?

**Comment by mbostock** [comment]
Two existing implementations:

* [baskerville/ciecam02](https://github.com/baskerville/ciecam02)
* [jrus/chromatist](https://github.com/jrus/chromatist)

**Comment by mbostock** [comment]
We probably should consider first the CAM02-UCS space proposed by [Luo et al.](http://dx.doi.org/10.1002/col.20227). A python implementation:

* [njsmith/colorspacious](https://github.com/njsmith/colorspacious)

**Comment by Deepblue129** [comment]
+1

**Comment by mbostock** [comment]
* [connorgr/d3-cam02](https://github.com/connorgr/d3-cam02)

**Comment by mbostock** [comment]
The current plan is to implement CIECAM16 as a standalone module, [d3-cam16](https://github.com/d3/d3-cam16).
