### ISSUE TITLE
Fix prototype.constructor.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-color#25]
The current definition obliterates the `constructor` property.

- [ ] Color
- [ ] Rgb
- [ ] Hsl
- [ ] Lab
- [ ] Hcl
- [ ] Cubehelix

**Comment by jonahwilliams** [comment]
I might be wrong, but this should be as easy as adding a few lines like
`color.prototype.constructor = Color;` after each one of the prototype assignments.  I'd be happy to open a PR to add them.

**Comment by mbostock** [comment]
No need; I’m already doing it. But thank you.
