### ISSUE TITLE
non-es6 version?

### ISSUE THREAD

**Issue by jay8t6** [d3/d3-color#28]
Can you create a transpiled version of this project to your bower repo for browsers that arent es6 compliant?

**Comment by mbostock** [comment]
This project already includes a transpiled UMD bundle for non-ES6 environments. As described in the README you can download the UMD bundle as an attached zipfile on the releases page, using npm install d3-color, from https://npmcdn.com/d3-color/ (look in build/) or from d3js.org as linked from the README.

**Comment by jay8t6** [comment]
we are using bower to install our project dependencies, thats why I wanted to know if its possible to download the transpiled version via bower. It would be perfect if that build folder is available in this repo. Any reason why its not included?

**Comment by mvolkmann** [comment]
Yes, it would be great if a transpiled version was available via bower so I could easily use it in a Polymer project.

**Comment by mbostock** [comment]
The reason I don’t store generated files in git repositories is that it is incredibly inconvenient for development. This is a serious design limitation of Bower and why I’ve needed to create dedicated secondary git repositories to support d3 and topojson (see https://github.com/mbostock-bower). However there’s no way I’m doing that for all the new D3 repositories.

I believe Bower can install from npm or from a URL, so use that. Or use curl and download it from https://npmcdn.com/d3-color/build/. If that doesn’t work, you could try petitioning the Bower maintainers; I am no longer supporting any publishing systems beyond npm and GitHub releases.

**Comment by jay8t6** [comment]
Makes sense. Thanks! It looks like bower does install from external urls.
