### ISSUE TITLE
CIEDE2000 color difference

### ISSUE THREAD

**Issue by danburzo** [d3/d3-color#48]
In the spirit of _I couldn't help it_ I've ported all the color difference metrics to work with d3-color here 👉  https://github.com/danburzo/d3-color-difference

Out of them the euclidean distances are trivial to compute by end-users, and from the rest CIEDE2000 is supposedly the most accurate, and a hassle to implement. May be a good addition to d3-color itself, or is it preferable as a separate package?

(Oooh, I missed [this notebook](https://beta.observablehq.com/@mbostock/measuring-color-difference)!)

**Comment by Fil** [comment]
Here's Mike's notebook refactored as a function:
https://observablehq.com/@fil/ciede2000

(And………… I had missed this issue :^) )

**Comment by Fil** [comment]
It's an interesting function but I don't mind having it in a separate module. Maybe it could be easier to discover with a link in this module’s README, and a more demo notebooks? There are already quite a few links in the "For additional color spaces, see:" paragraph, which could have a title ("Extensions") and add this module?

**Comment by danburzo** [comment]
> It's an interesting function but I don't mind having it in a separate module.

Yep, a separate module works for me.

**Comment by danburzo** [comment]
I think this issue can be closed now that `d3-color-difference` is mentioned in the README.
