### ISSUE TITLE
d3.hsl doesnt seem to work with grey scale values

### ISSUE THREAD

**Issue by nonmetalhail** [d3/d3-color#73]
Seems like whenever I have a color where the saturation is 0% or the lightness is 0% or 100%, I get `NaN` values in the returned color object.

Easiest to see the various examples here:
[https://observablehq.com/d/f7636f7695376a03](https://observablehq.com/d/f7636f7695376a03)

But, for example:
`d3.hsl('#ffffff')` returns `{h: NaN, s: NaN, l: 1, opacity: 1}`

**Comment by mbostock** [comment]
This is intended. See:

https://observablehq.com/@d3/achromatic-interpolation

**Comment by mootari** [comment]
Might be a good idea to add a note to the readme (unless it's already there and I missed it)?
