### ISSUE TITLE
Brightening black in RGB

### ISSUE THREAD

**Issue by maltebaer** [d3/d3-color#80]
What is the desired behaviour of brightening black colour? Right now it will return black.

```js
const brighter = d3.rgb("#000000").brighter(); // {b: 0, g: 0, opacity: 1, r: 0}
```

**Comment by Fil** [comment]
Interesting question.  https://github.com/d3/d3-color#color_brighter says “The behavior of this method [brighter] is dependent on the implementing color space.”

and indeed d3.lch(d3.rgb("#000")).brighter().hex() // "#2c2c2c"

**Comment by danburzo** [comment]
There's no official definition of a _brighten_ function, and as @Fil mentions, the behavior depends on the color space. in RGB, the effect on black follows the definiton: `C' = C * Math.pow(1.42, k)`. This corresponds to how [the CSS `brightness` filter works](https://drafts.fxtf.org/filter-effects/#brightnessEquivalent) (`C' = slope * C + intercept`); it, too, leaves black intact.

**Comment by maltebaer** [comment]
Thanks for your answers.

Converting to HCL color space will work as desired, in my scenario.
