### ISSUE TITLE
Incorrect conversion from HCL / LCH to hex or rgb

### ISSUE THREAD

**Issue by neil-oliver** [d3/d3-color#85]
Firstly, thank you @mbostock for all of your incredible work, every time i have no clue how i am going to achieve something, it seems that d3 has already created a solution. 

One small issue i have spotted is that when creating a d3.hcl object (example used is d3.hcl(15,100,65)) and converting to either rgb or hex (using both .rgb or d3.rgb()), it provides the wrong values. Output from this conversion is #FF0077 and it should be #F8766D.

Tested with d3 5.9.2 & 6.2.0

Edit: The conversion seems to be the same as Chroma.js so maybe this isn't a d3 issue? The output varies massively to this http://hclwizard.org/hclcolorpicker/ which i think is using R to generate the colors / graphics

**Comment by danburzo** [comment]
Hi @neil-oliver, it's just a confusion of terms. In the Color space R package, HCL refers to the [polar form of the CIELUV color space](http://colorspace.r-forge.r-project.org/reference/polarLUV.html), while in D3 (and Chroma) HCL refers to the the polar form of the CIELAB color space. [See also #64](https://github.com/d3/d3-color/issues/64).

**Comment by neil-oliver** [comment]
Excellent, thanks for the clear explanation. I will wait for d3.luv to be implemented.
