### ISSUE TITLE
Does the Common JS version of the module work?

### ISSUE THREAD

**Issue by watson** [d3/d3-color#95]
This modules ships with a Common JS version under a `dist` directory:

![image](https://user-images.githubusercontent.com/10602/127149686-e51a96c0-cb9f-4adf-b7d7-47a8ea98dfe3.png)

However, the `exports` field in `package.json`, is defined as such:

https://github.com/d3/d3-color/blob/7d61bbe6e426a7f3d3f4520a8b31cfc92dc69ee7/package.json#L35-L38

As far as I can see, these two entries doesn't really make any sense. E.g. there's no way that I know of to require the `umd` version of this package. Either the `exports` keys should all be prefixed with `./` which would require users to to update their `require` and `import` statements accordingly, or the two keys should be `require` and `import` instead of `umd` and `default`. In both cases the `./dist/d3-color.min.js` key should be `./dist/d3-color.min.cjs` (notice the `cjs` ending) since this is a package of `"type": "module"`.

**Comment by mbostock** [comment]
CommonJS is no longer supported as of [d3-color 3.0](https://github.com/d3/d3-color/releases/tag/v3.0.0). In Node (or other environments that use package.json), you must use the ES module import. The UMD is intended for browsers, typically as either a vanilla script or AMD.
